In [1]:
import numpy as np

In [3]:
# array creation, 1d array
a = np.array([1,2,3,4,5])   
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)  #ndarray = non dimensional array

numpy.ndarray

In [5]:
print(a + b)
print(a - b)
print(a * b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [7]:
# creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [10]:
# creating 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3) 
type(a3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [12]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [14]:
print(a2.ndim)   # to check the dimension 
print(a3.ndim)

2
3


In [15]:
print(a2.dtype)  # datatype is integer

int64


In [21]:
np.arange(11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [28]:
np.random.randint(1,11,size =(2,3))

array([[7, 4, 1],
       [3, 9, 1]], dtype=int32)

In [31]:
np.random.randint(1,11,size =(3,2,3))

array([[[1, 9, 2],
        [1, 1, 1]],

       [[2, 5, 9],
        [3, 3, 4]],

       [[7, 4, 8],
        [8, 8, 2]]], dtype=int32)

In [32]:
x = np.random.randint(1,21,size =(2,2))
y = np.random.randint(1,21,size =(2,2))
print(x)
print(y)

[[20 20]
 [19 12]]
[[ 8  1]
 [ 6 18]]


In [33]:
print(x + y)
print(x - y)
print(x * y)

[[28 21]
 [25 30]]
[[12 19]
 [13 -6]]
[[160  20]
 [114 216]]


In [34]:
# '@' is used for matrix multiplication
# 1st method
print(x @ y)   

[[280 380]
 [224 235]]


In [35]:
# 2nd method
np.dot(x,y)

array([[280, 380],
       [224, 235]], dtype=int32)

In [36]:
# product
x.prod()

np.int64(91200)

In [40]:
x.mean()
y.mean()

np.float64(8.25)

In [43]:
print(x)

[[20 20]
 [19 12]]


In [41]:
b = x.mean(axis=0)  # 0 means column wise
print(b)

[19.5 16. ]


In [42]:
c = x.mean(axis=1)  # 1 means row wise
print(c)

[20.  15.5]


In [46]:
print(x.sum())
print(x.std())  # standard deviation
print(x.var())  # variance


71
3.344772040064913
11.1875


In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))


5.0
3.0
7.0


In [52]:
arr2 = np.random.randint(11,100, (4,4))
print(arr2)

[[41 12 82 66]
 [70 76 22 75]
 [67 34 15 92]
 [26 85 88 62]]


In [53]:
# to convert a matrix from one to another
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[41 12 82 66 70 76 22 75]
 [67 34 15 92 26 85 88 62]]
8x2
[[41 12]
 [82 66]
 [70 76]
 [22 75]
 [67 34]
 [15 92]
 [26 85]
 [88 62]]
