In [2]:
import numpy as np

In [3]:
# array creation, 1d array
a = np.array([1,2,3,4,5])   
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)  #ndarray = non dimensional array

numpy.ndarray

In [5]:
print(a + b)
print(a - b)
print(a * b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
# creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
# creating 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3) 
type(a3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [8]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [9]:
print(a2.ndim)   # to check the dimension 
print(a3.ndim)

2
3


In [10]:
print(a2.dtype)  # datatype is integer

int64


In [11]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.random.randint(1,11,size =(2,3))

array([[8, 3, 7],
       [7, 8, 1]], dtype=int32)

In [15]:
np.random.randint(1,11,size =(3,2,3))

array([[[6, 3, 3],
        [7, 7, 5]],

       [[4, 6, 5],
        [5, 7, 1]],

       [[4, 7, 9],
        [7, 4, 4]]], dtype=int32)

In [16]:
x = np.random.randint(1,21,size =(2,2))
y = np.random.randint(1,21,size =(2,2))
print(x)
print(y)

[[10  7]
 [11 11]]
[[ 3 11]
 [ 5 18]]


In [17]:
print(x + y)
print(x - y)
print(x * y)

[[13 18]
 [16 29]]
[[ 7 -4]
 [ 6 -7]]
[[ 30  77]
 [ 55 198]]


In [18]:
# '@' is used for matrix multiplication
# 1st method
print(x @ y)   

[[ 65 236]
 [ 88 319]]


In [19]:
# 2nd method
np.dot(x,y)

array([[ 65, 236],
       [ 88, 319]], dtype=int32)

In [20]:
# product
x.prod()

np.int64(8470)

In [21]:
x.mean()
y.mean()

np.float64(9.25)

In [22]:
print(x)

[[10  7]
 [11 11]]


In [23]:
b = x.mean(axis=0)  # 0 means column wise
print(b)

[10.5  9. ]


In [24]:
c = x.mean(axis=1)  # 1 means row wise
print(c)

[ 8.5 11. ]


In [25]:
print(x.sum())
print(x.std())  # standard deviation
print(x.var())  # variance


39
1.6393596310755
2.6875


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))


5.0
3.0
7.0


In [27]:
arr2 = np.random.randint(11,100, (4,4))
print(arr2)

[[63 17 63 77]
 [91 60 85 43]
 [54 68 79 25]
 [89 30 17 53]]


In [28]:
# to convert a matrix from one to another
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[63 17 63 77 91 60 85 43]
 [54 68 79 25 89 30 17 53]]
8x2
[[63 17]
 [63 77]
 [91 60]
 [85 43]
 [54 68]
 [79 25]
 [89 30]
 [17 53]]


In [29]:
print(arr2)

[[63 17 63 77]
 [91 60 85 43]
 [54 68 79 25]
 [89 30 17 53]]


In [34]:
print(arr2[0])   # oth row
print(arr2[0,1]) # 0th row 1st column
print(arr2[-1])  # last row 
print(arr2[:3])  # 0th to 2nd row
print(arr2[1:])  # 1st to last row


[63 17 63 77]
17
[89 30 17 53]
[[63 17 63 77]
 [91 60 85 43]
 [54 68 79 25]]
[[91 60 85 43]
 [54 68 79 25]
 [89 30 17 53]]


In [44]:
arr2 > 30

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False, False,  True]])

In [46]:
y = arr2[arr2>50]
z = y.reshape(4,2)
print(z)

ValueError: cannot reshape array of size 11 into shape (4,2)